apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: localhost
spec:
  service:
    type: LoadBalancer
 
 # RabbitMQ properties
  rabbitmq:
   addresses: localhost:5672
   adminAddresses: http://localhost:15672
   nodes: rabbit@localhost
   username: guest
   password: guest
   virtual_host: /
   useSSL: false
   sslProperties:
   ssl:
     keyStore:
     keyStorePassphrase:
     trustStore:
     trustStorePassphrase:
   channelCacheSize: 100
