apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
spec:
  tls:
  - hosts:
      - www.twatter.nl
    secretName: twatter2
  rules:
  - host: www.twatter84.nl 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ui-svc
            port:
              number: 80
  - host: twatter84.gateway.nl
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: gateway-svc
            port:
              number: 8123
  - host: twatter84.userservice.nl
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: userservice-svc
            port:
              number: 5002
  - host: twatter84.postservice.nl
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: postservice-svc
            port:
              number: 5001
