apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout
  annotations:
spec:
  rules:
    http:
      paths:
      - pathType: Prefix
        path: /account
        backend:
          service:
            name: account-svc
            port:
              number: 5002
      paths:
      - pathType: Prefix
        path: /gateway
        backend:
          service:
            name: gateway-svc
            port:
              number: 8123
      paths:
      - pathType: Prefix
        path: /write
        backend:
          service:
            name: write-svc
            port:
              number: 5002
      paths:
      - pathType: Prefix
        path: /topic
        backend:
          service:
            name: topic-svc
            port:
              number: 5004
