apiVersion: v1
kind: Service
metadata:
  name: postservice-svc
  labels:
    run: postservice-svc
spec:
  type: NodePort
  ports:
  - port: 5005
    nodePort: 30003
    protocol: TCP
  selector:
    run: postservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
spec:
  selector:
    matchLabels:
      run: postservice
  replicas: 1
  template:
    metadata:
      labels:
        run: postservice
    spec:
      containers:
      - name: postservice
        image: robindewitte/postservice:postservice0.1.2
        ports:
        - containerPort: 5005
