apiVersion: v1
kind: Pod
metadata: 
  name: sqlserver
spec:
  initContainers:
  - name: database1
    image: fictivusaccount
    command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
    volumeMounts:
    - mountPath: "/var/opt/mssql"
      name: sqldata-storage
  volumes:
  - name: sqldata-storage
    persistentVolumeClaim:
      claimName: dbclaim

  containers:
  - image: mcr.microsoft.com/mssql/server
    name: database1
    volumeMounts:
    - mountPath: "/var/opt/mssql/data"
      name: sqldata-storage
    env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sql-password
          key: sa_password
    - name: MSSQL_PID
      value: Developer
