apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment2
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql2
  template:
    metadata:
      labels:
        app: mssql2
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql2
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql2
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb2
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb2
        persistentVolumeClaim:
          claimName: mssql-data2
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment2
spec:
  selector:
    app: mssql2
    namespace: external
spec: 
  type: ExternalName
  externalName: 10.0.2.2
type: LoadBalancer
