apiVersion: v1
kind: Service
metadata:
  name: userservice-svc
  labels:
    run: userservice-svc
spec:
type: NodePort
  ports:
  - port: 5002
  NodePort: 30002
    protocol: TCP
  selector:
    run: userservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      run: userservice
  replicas: 1
  template:
    metadata:
      labels:
        run: userservice
    spec:
      containers:
      - name: userservice
        image: robindewitte/twatter:userservice
        ports:
        - containerPort: 5002
